FROM nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04
 
RUN apt-get update && apt-get install -y software-properties-common && add-apt-repository ppa:deadsnakes/ppa \
    && apt-get update \
    && apt-get install -y build-essential python3.6 python3.6-dev python3-pip python3.6-venv git \
    && apt-get install -y wget curl libglib2.0-0 libsm6 libxext6 libxrender-dev libturbojpeg ffmpeg \
    # update pip
    && python3.6 -m pip install pip --upgrade \
    && python3.6 -m pip install wheel \
    && ln -s /usr/bin/python3.6 /usr/bin/python \
    && apt-get clean && rm -rf /var/lib/apt/lists/*
